# escape=`

FROM mcr.microsoft.com/windows/servercore:ltsc2022-amd64 as base-runtime

ENV `
    # Configure web servers to bind to port 8080 when present
    ASPNETCORE_HTTP_PORTS=8080 `
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true `
    # .NET Runtime version
    DOTNET_VERSION=8.0.11 `
    # ASP.NET Core version
    ASPNET_VERSION=8.0.11

# Install .NET Runtime
RUN powershell -Command `
        $ErrorActionPreference = 'Stop'; `
        $ProgressPreference = 'SilentlyContinue'; `
        `
        Invoke-WebRequest -OutFile dotnet.zip https://dotnetcli.azureedge.net/dotnet/Runtime/$Env:DOTNET_VERSION/dotnet-runtime-$Env:DOTNET_VERSION-win-x86.zip; `
        $dotnet_sha512 = 'CB80A41EA64DB17F2CC21390FEFEAC7342E965FBA3BB6F768C51FDCF7271FBD1399EAAF33EC1162BC206E47BC8D296D28DDAD2139C8A770D02E62FA90AF49A32'; `
        if ((Get-FileHash dotnet.zip -Algorithm sha512).Hash -ne $dotnet_sha512) { `
            Write-Host 'CHECKSUM VERIFICATION FAILED!'; `
            exit 1; `
        }; `
        `
        mkdir $Env:ProgramFiles\dotnet; `
        tar -oxzf dotnet.zip -C $Env:ProgramFiles\dotnet; `
        Remove-Item -Force dotnet.zip

# Install ASP.NET Core Runtime
RUN powershell -Command `
        $ErrorActionPreference = 'Stop'; `
        $ProgressPreference = 'SilentlyContinue'; `
        `
        Invoke-WebRequest -OutFile aspnetcore.zip https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/$Env:ASPNET_VERSION/aspnetcore-runtime-$Env:ASPNET_VERSION-win-x86.zip; `
        $aspnetcore_sha512 = 'C0399CF5B217703F1142F3D44A29EB443621F6038FA1BF602C3C661B5A55C13F18A74F90A6ABC3D1C1E1B6A4232A7AB7B9BB19BA7F3454387097E98F79B5FDD2'; `
        if ((Get-FileHash aspnetcore.zip -Algorithm sha512).Hash -ne $aspnetcore_sha512) { `
            Write-Host 'CHECKSUM VERIFICATION FAILED!'; `
            exit 1; `
        }; `
        `
        tar -oxzf aspnetcore.zip -C $Env:ProgramFiles\dotnet ./shared/Microsoft.AspNetCore.App; `
        Remove-Item -Force aspnetcore.zip

RUN setx /M PATH "%PATH%;C:\Program Files\dotnet"
RUN setx /M DOTNET_ROOT "C:\Program Files\dotnet"

FROM mcr.microsoft.com/dotnet/sdk:8.0-windowsservercore-ltsc2022 AS sdk
WORKDIR /app

COPY ./ ./
RUN dotnet publish -c Release -o out

FROM base-runtime as runtime
WORKDIR /app
COPY --from=sdk /app/out .
RUN DIR
ENTRYPOINT ["winx86-container.exe"] 